# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr_app', '0002_auto_20171116_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
