# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lr_app', '0003_users_desc'),
        ('msg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='user',
            new_name='for_user',
        ),
        migrations.AddField(
            model_name='messages',
            name='poster',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='lr_app.Users'),
            preserve_default=False,
        ),
    ]
